config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'sites#request_form'

  resources :sites, only: [:index, :destroy] do
    collection do
      get :request_form
      get :analysis
    end
    
    resources :pages, only: :show, shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :site

  validates :url, presence: true, format: URI::regexp, uniqueness: { scope: [:site_id, :url] }
end

app/models/robots_txt.rb
class RobotsTxt < ApplicationRecord
  belongs_to :site

  def find_sitemap_path
    instruction = content.split("\n").select { |i| i =~ /^sitemap*/i }
    return unless instruction.any?

    instruction.first.split(" ").last
  end
end

app/models/site.rb
class Site < ApplicationRecord
  DOMAIN_REGEXP=/\A(((?!-))(xn--|_{1,1})?[a-z0-9-]{0,61}[a-z0-9]{1,1}\.)*(xn--)?([a-z0-9][a-z0-9\-]{0,60}|[a-z0-9-]{1,30}\.[a-z]{2,})\z/

  has_many :pages, dependent: :destroy
  has_one :robots_txt, dependent: :destroy

  validates :domain, presence: true, uniqueness: true, format: DOMAIN_REGEXP

  def https?
    https
  end

  def www_subdomain?
    www_subdomain
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :registerable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find(params[:id])
    @parsed_page = Services::PageParser.new(@page).call
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :destroy]

  def analysis
    @site = Services::SiteAnalyzer.new(params[:domain]).call
  end

  def request_form; end

  def index
    @sites = Site.paginate(page: params[:page], per_page: params[:per_page]).order('created_at DESC')
  end

  def destroy
    @site = Site.find(params[:id])
    @site.destroy
    redirect_to sites_path, alert: "Site was successfuly deleted from database."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    title SEOService
    
    meta charset="utf-8"
    meta name='viewport' content="width=device-width, initial-scale=1, shrinkto-fit=no"
    meta name='description' content="small SEO-service with parsing of sitemap.xml and page content"

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 

  body
    .container
      = render 'shared/header'
      = render 'shared/flash'
      = yield

app/views/pages/show.html.slim
h1 Parsed page

.page-info
  p
    strong
      | site: #{@page.site.domain}
      br
      |  url: #{@page.url}

.parsed-info
  .meta-info
    h2 meta info

    table.table.table-striped
      thead
        tr
          th element
          th content
      tbody
        tr
          td title:
          td= @parsed_page[:title]
        tr
          td charset:
          td= @parsed_page[:charset]
        -@parsed_page[:meta_tags].each do |mt|
          tr
            td= mt.first
            td= mt.last
  
  .html-tags-info
    h2 html tags info
    
    .headers
      h3 Headers
      table.table.table-striped
        -@parsed_page[:headers].each do |h_type, values|
          -values.each do |header|
            tr
              td= h_type
              td= header
      hr
    
    .links
      h3 Links

      table.table.table-striped
        -@parsed_page[:links].each do |l|
          tr
            td= l[:text]
            td= l[:href]
            td= link_to "go", l[:href], target: '_blank'
      hr
    
    .lists
      h3 Lists:
      
      .card
        h4.card-header Page has #{@parsed_page[:lists][:ul][:counter]} unordered lists
        .card-body
          p
            strong samples:
          -if @parsed_page[:lists][:ul][:samples]
            -@parsed_page[:lists][:ul][:samples].each do |sample|
              p= sample
      
    
      .card
        h4.card-header Page has #{@parsed_page[:lists][:ol][:counter]} ordered lists
        .card-body
          p
            strong samples:
          -if @parsed_page[:lists][:ol][:samples]
            -@parsed_page[:lists][:ol][:samples].each do |sample|
              p= sample
    hr

    .tables
      .card
        h4.card-header Page has #{@parsed_page[:tables][:counter]} tables
        .card-body 
          p
            strong samples:
          
          -if @parsed_page[:tables][:samples]
            -@parsed_page[:tables][:samples].each do |sample|
              table
                | #{{sample}}
      

app/views/shared/_flash.html.slim
- if notice   
  p.notice.alert.alert-success.m-3
    = notice
- if alert
  p.alert.alert-danger.m-3
    = alert

app/views/shared/_header.html.slim
.header
  .navbar.navbar-light.bg-light
    .navbar-brand
      = link_to  "SEO-service", root_path
    .justify-content-end
      -if current_user
        .nav-item = link_to "Admin panel", sites_path, class: "nav-link-active"
        .nav-item = link_to "Exit", destroy_user_session_path, method: :delete, class: "nav-link-active"
      -else
        .nav-item = link_to "Admin entrance", new_user_session_path, class: "nav-link-active"
      

app/views/sites/_pages.html.slim
.pages
  h3.card-subtitle Has #{@site.pages.count} pages
  p
    = link_to 'show pages', '#', remote: true, class: 'show-pages btn btn-info m-3', role: 'button'
    = link_to 'hide pages', '#', remote: true, class: 'hide-pages btn btn-info hidden m-3', role: 'button'  
  table.hidden.pages-table.table.table-striped.table-hover
    tbody
      - @site.pages.each do |page| 
        tr
          td style="word-break:break-all;"
            = page.url
          td
            .btn-group role="group" aria-label="page-btn-group"
              = link_to "go to the page", page.url, target: '_blank',  class: 'btn btn-primary', role: 'button'
              = link_to "parse the page", page_path(page), target: '_blank', class: 'btn btn-danger', role: 'button'
  p= link_to 'hide pages', '#', remote: true, class: 'hide-pages btn btn-info hidden m-3', role: 'button'

app/views/sites/_robots.html.slim
.robots_txt
  button type="button" class="btn btn-info m-3" data-toggle="modal" data-target="#robotsFile"
    | show robots.txt


  div class='modal fade' id="robotsFile" tabindex="-1" role="dialog" aria-labelledby="robotsFileLabel" aria-hidden="true"
    .modal-dialog role="document"
      .modal-content
        .modal-header
          h5.modal-title id="robotsFileLabel" robots.txt
          button.close type="button" data-dismiss="modal" aria-label="Close"
            span aria-hidden="true" &times;

        .modal-body
          .card
            .card-body
              pre= @site.robots_txt&.content

        .modal-footer
          button type="button" class="btn btn-secondary" data-dismiss="modal" Close

app/views/sites/analysis.html.slim
- if @site
  .card
    .card-body
      h1.card-title=  "Analysis of #{@site.domain}"
      ul.list-group
        -if @site.https?
          li.list-group-item = "Has HTTPS"
        -else 
          li.list-group-item = "Has NOT HTTPS"
        -if @site.www_subdomain?
          li.list-group-item = "Has WWW subdomain"
        -else
          li.list-group-item = "Has NOT WWW subdomain"

      = render 'robots'
      = render 'pages'
      
      p= link_to  "Back to request page", root_path, class: 'card-link', role: 'button'

- else
  .card
    .card-body
      h4.card-title Site doesn't exists or not accessible at that moment

    p= link_to  "Back to request page", root_path, class: 'card-link', role: 'button'

app/views/sites/index.html.slim
.pagination.m-3
  = will_paginate @sites

table.table.table-striped
  thead
    tr 
      th domain name
      th pages
      th was created at
      th was updated at
      th actions

  -@sites.each do |site|
    tr
      td= site.domain
      td= site.pages.count
      td= site.created_at
      td= site.updated_at
      td
        .btn-group role="group" aria-label="page-btn-group"
          = link_to "analysis", analysis_sites_path(params: {domain: site.domain}), class: 'btn btn-primary', role: 'button'
          = link_to "destroy", site_path(site), method: :delete, class: 'btn btn-danger', role: 'button'

.pagination.m-3
  = will_paginate @sites
p
  = form_with url: sites_path, method: :get,local: true do |f|
    =f.label :per_page, "Sites per page: "
    =f.number_field :per_page, value: '30', max: 100, min: 20, step: 10
    =f.submit "show"

app/views/sites/request_form.html.slim
.request-panel
  = form_with url: analysis_sites_path, method: :get, local: true do |f|
    p
      .input-group
        .input-group-prepend
          span.input-group-text id="inputGroup-sizing-default" domain:
        = f.text_field :domain, placeholder: 'enter domain name', class: 'form-control'
        = f.submit "Go", class: 'btn btn-success', role: 'button'